language: generic

services:
  - docker

script:
  - make docker

deploy:
  provider: releases
  # https://github.com/settings/tokens
  # Add variable TOKEN in TravisCI settings
  api_key: $TOKEN
  file: master-thesis-$(date +%d.%m.%Y_%R).pdf presentation/presentation.pdf
  skip-cleanup: true
